# Generated by Django 4.2.6 on 2023-12-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('info_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('channel_title', models.CharField(blank=True, max_length=50)),
                ('channel_id', models.CharField(max_length=80)),
                ('channel_thumbnail', models.CharField(blank=True, max_length=120)),
                ('channel_url', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
