# Generated by Django 4.2.6 on 2023-12-01 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channel_url',
        ),
    ]
