# Generated by Django 4.2.6 on 2023-12-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_remove_channel_channel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_thumbnail',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
